apiVersion: v1
kind: Service
metadata:
  name: coder
  annotations:
    dev.okteto.com/auto-ingress: "private"
  labels:
    {{- include "movies.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
